legs_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - FL_hip_joint
    - FL_thigh_joint
    - FL_calf_joint
    - FR_hip_joint
    - FR_thigh_joint
    - FR_calf_joint
    - RL_hip_joint
    - RL_thigh_joint
    - RL_calf_joint
    - RR_hip_joint
    - RR_thigh_joint
    - RR_calf_joint
  gains:
    FL_hip_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    FL_thigh_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    FL_calf_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    FR_hip_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    FR_thigh_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    FR_calf_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    RL_hip_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    RL_thigh_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    RL_calf_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    RR_hip_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    RR_thigh_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    RR_calf_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1