defaults:
    # - _self_
    # - agent: cpn # forward model will also be added in the future - TODO: maybe add a wrapper agent class?
    # - encoder: resnet18
    # - trans: mlp
    # - optimizer: adam
    - agent: pli
    - optimizer: adam

model:
  _target_: contrastive_learning.models.custom_models.LinearInverse
  input_dim: ??? # They will be set according to the rest of the config
  action_dim: ???
  hidden_dim: ???

# this needs to be specified manually
experiment: pli

seed: 42
device: cuda

agent_type: pli # cpn / pli
dataset_type: state # State or visual for now
train_epochs: 1000
save_frequency: 10 # Frequency to save the model - there will be a test in each step
train_dset_split: 0.8

# Hyperparameters to be used everywhere
batch_size: 64
lr: 1e-2
weight_decay: 1e-5
z_dim: 1000 # resnet18 gives out 1000 dimensions (needed for cpn)
pos_dim: 8 # this is needed for pli
hidden_dim: 64
action_dim: 2

distributed: true
num_workers: 4
world_size: 1
num_gpus: 4

fps: 15 # This should be the same as the all the fps in saving - little differences are not going to be taken
# sec_interval: 0.33 # seconds to separate two timesteps
frame_interval: 8 # Will be equal to fps * sec_interval - frames to separate two timesteps
video_type: color # NOTE: you could remove this if you want to use both

data_dir: /home/irmak/Workspace/DAWGE/src/dawge_planner/data
checkpoint_dir: ??? # Will be set to hydra dir inside the code

# logger
log_frequency: 1

# hydra configuration - should be received separately
hydra:
    run:
        dir: /home/irmak/Workspace/DAWGE/contrastive_learning/out/${now:%Y.%m.%d}/${now:%H-%M}_${experiment}